name: Version

on:
  push:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run test

  version:
    needs: [ test ]
    name: Bump version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: phips28/gh-action-bump-version@master
        name: Bump JSR version
        env:
          PACKAGE_FILENAME: jsr.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          skip-tag: true
          skip-push: true
      - uses: phips28/gh-action-bump-version@master
        name: Bump NPM version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: v
